name: Login to ECR Anvil
description: Repository for RV approved container images
inputs:
    aws-access-key-id:
      description: "AWS access key ID for ECR"
      required: true
    aws-secret-access-key:
      description: "AWS secret access key for ECR"
      required: true

runs:
  using: "composite"
  steps:
  - name: Configure AWS credentials
    uses: aws-actions/configure-aws-credentials@v1
    with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: us-east-1
   
  - uses: aws-actions/amazon-ecr-login@v1
    with:
      registries: '12345678901'
