name: Install EKS Dependencies
description: Installs eksctl and kubectl

runs:
  using: "composite"
  steps:

    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.23.6'

    - name: Install eksctl
      shell: bash
      run: |
        curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bin        
